GitHubRGI/swagd

Gdal2Tiles/src/com/rgi/g2t/GdalTileJob.java
=> testing cli request-pull cmd

Common/src/com/rgi/common/Range.java, Common/test/com/rgi/common/coordinates/referencesystem/profile/CrsProfileFactoryTest.java, Common/test/com/rgi/common/test/RangeTest.java
Tests for Range class in common
=> #2 progress towards testing common Range

Common/test/com/rgi/common/tile/scheme/TileMatrixDimensionsTest.java, Common/test/com/rgi/common/tile/scheme/ZoomTimesTwoTest.java
Tests for TileMatrixDimensions and ZoomTimesTwo classes
=> Test com.rgi.tile.scheme

Common/src/com/rgi/common/tile/store/TileStoreReader.java, Common/src/com/rgi/common/util/ImageUtility.java, Gdal2Tiles/src/com/rgi/g2t/RawImageTileReader.java, GeoPackage/src/store/GeoPackageReader.java, GeoViewer/src/org/openstreetmap/gui/jmapviewer/TileStoreLoader.java
Problem was that the CrsCoordinate returned is on the UpperLeft corner of the tile and TMS is in LowerLeft therefore returning the incorrect tiles
=> Fixing coordinate transform in viewer

GeoViewer/src/com/rgi/view/MapViewWindow.java, GeoViewer/src/com/rgi/view/TileStoreTileSource.java
this allows the zoom slider to zoom in and out to only the min and max
zooms
=> implemented tileSource to fix the zoom slider

Gdal2Tiles/src/com/rgi/g2t/GdalTileJob.java, Gdal2Tiles/src/com/rgi/g2t/RawImageTileReader.java, Gdal2Tiles/src/com/rgi/g2t/Tiler.java, Gdal2Tiles/src/utility/GdalUtility.java, RGISuite/src/com/rgi/suite/tilestoreadapter/rawimage/RawImageTileStoreReaderAdapter.java, RGISuite/src/com/rgi/suite/uielements/windows/TilerWindow.java
Added tiling for all raster zoom levels and progress monitoring.
What is left to do:
* enable transparency in tiles generated
* finish the javadoc for all new functions and refactorings
Ikuzou, Release 1.0-chan!
=> Tiler debugging

VerifierTool/pom.xml, pom.xml
Adding the Verifier tool to the SWAGD pom.xml file, editing the VerificationTool/pom.xml to establish parent relationship in the maven workflow.
=> Adding verifier tool to maven build, #185

GeoPackage/src/com/rgi/geopackage/verification/Verifier.java
the column names with case insensitive searches.  This is changed bc
SQLite does not do case sensitive searches
=> Changing it to a treeMap allows us to check

README.md
=> 1.1 update

GeoPackage/src/com/rgi/geopackage/GeoPackage.java, GeoPackage/src/utility/DatabaseUtility.java
Significant packaging performance gained.
=> Adding function to change journal mode to memory, #208

.travis.yml, Common/pom.xml, Common/src/com/rgi/common/Memoize2.java, GeoPackage/pom.xml, pom.xml
Excludes Metadata Verifier and Schema Verifier tests
=> Unit Test Ignores

Common/test/com/rgi/common/Memoize2Test.java, RoutingExtension/src/com/rgi/geopackage/extensions/routing/router/astar/AStar.java, pom.xml
* Add tests for Memoize2.java
* fix memoize import in AStar
* ignore a few exception classes in test coverage
=> add memoize tests

Common/test/com/rgi/common/Memoize2Test.java
=> adding null test for memoize

.idea/inspectionProfiles/SWAGD.xml, Common/test/com/rgi/common/PairTest.java
* creating unit tests for pair class in common
=> adding pair tests

pom.xml
* Excluding packager from unit tests
=> ignore packager class from tests

Gdal2Tiles/src/utility/GdalUtility.java, GeoViewer/src/com/rgi/view/MapViewWindow.java, RGISuite/src/utility/TileStoreUtility.java
* fixing issue where certain data formats could not be tiled due to unexpected SRS authority information.
=> fixing issue with authorities

.travis.yml, gdal_2.0.0_jni.sh
* Upgrade CI build scripts to use GDAL 2.0.0
=> Upgrade to GDAL 2.0.0

.idea/inspectionProfiles/SWAGD.xml, .idea/misc.xml, .idea/vcs.xml
* Removed vcs.xml from the idea folder, as IntelliJ complains about hg-git on my machine
* Moved jdk/jre name
* Removed a potentially deprecated linter rule
=> Intellij fixes

.idea/inspectionProfiles/SWAGD.xml, .idea/misc.xml, .idea/vcs.xml, gdal_2.0.0_jni.sh
* left out the detection of the correct directory to ignore gdal rebuilds
=> Gdal2.0 upgrade

Common/src/test/java/com/rgi/common/util/jdbc/JdbcUtilityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/githubrgi/swagd/373)
=> Missed two tests that needed .toURI()

.idea/misc.xml, Common/src/test/java/com/rgi/common/TestUtility.java, Common/src/test/java/com/rgi/common/util/jdbc/JdbcUtilityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/githubrgi/swagd/375)
=> Cleaned up test code

.idea/modules/Common/Common_test.iml, .idea/modules/DataProductionTools/DataProductionTools_main.iml, .idea/modules/DataProductionTools/DataProductionTools_test.iml, .idea/modules/DataProductionTools/libs/graphhopper/core/graphhopper_main.iml, .idea/modules/DataProductionTools/libs/graphhopper/core/graphhopper_test.iml, .idea/modules/DataProductionTools/libs/graphhopper/tools-lgpl/graphhopper-tools-lgpl_main.iml, .idea/modules/DataProductionTools/libs/graphhopper/tools-lgpl/graphhopper-tools-lgpl_test.iml, .idea/modules/DataProductionTools/libs/graphhopper/tools/graphhopper-tools_main.iml, .idea/modules/DataProductionTools/libs/graphhopper/tools/graphhopper-tools_test.iml, .idea/modules/DataStore/DataStore_test.iml, .idea/modules/Gdal2Tiles/Gdal2Tiles_main.iml, .idea/modules/Gdal2Tiles/Gdal2Tiles_test.iml, .idea/modules/GeoPackage/GeoPackage_test.iml, .idea/modules/GeoViewer/GeoViewer_test.iml, .idea/modules/NetworkExtension/NetworkExtension_test.iml, .idea/modules/Packager/Packager_test.iml, .idea/modules/RGISuite/RGISuite_main.iml, .idea/modules/RGISuite/RGISuite_test.iml, .idea/modules/RoutingExtension/RoutingExtension_test.iml, .idea/modules/SWAGD_test.iml, DataProductionTools/src/main/java/com/rgi/dem2gh/Dem2Graphhopper.java, DataProductionTools/src/main/java/com/rgi/dem2gh/TagElevationProvider.java, DataProductionTools/src/main/java/com/rgi/routingnetworks/dem/DemRoutingNetworkStoreReader.java, DataProductionTools/src/test/java/com/rgi/routingnetworks/GraphHopperTest.java, DataProductionTools/src/test/java/com/rgi/routingnetworks/TriangleRoutingNetworkStoreReaderTest.java, DataStore/src/main/java/com/rgi/store/routingnetworks/Utility.java, DataStore/src/main/java/com/rgi/store/routingnetworks/osm/OsmXmlRoutingNetworkStoreWriter.java, DataStore/src/main/java/com/rgi/store/routingnetworks/triangle/TriangleRoutingNetworkStoreReader.java, Gdal2Tiles/build.gradle, build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/githubrgi/swagd/393)
=> Data production tools
